# Generated by Django 4.2 on 2023-04-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("handbook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SenateMeeting",
            fields=[
                ("number", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "announcement",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
                ("lastModified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SenatePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=2)),
                ("proposal", models.CharField(blank=True, max_length=512, null=True)),
                ("resolution", models.CharField(blank=True, max_length=512, null=True)),
                ("approvalPending", models.BooleanField(default=True)),
                ("approved", models.BooleanField(default=False)),
                ("handbookPointNewText", models.TextField(blank=True, null=True)),
                (
                    "handbookPoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versionHistory",
                        to="handbook.handbookpoint",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subPoints",
                        to="senateMeeting.senatepoint",
                    ),
                ),
                (
                    "senateMeeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senatePoints",
                        to="senateMeeting.senatemeeting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annexure",
            fields=[
                ("number", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "attachedPDF",
                    models.FileField(default=None, null=True, upload_to="annexures/"),
                ),
                (
                    "senateMeeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annexures",
                        to="senateMeeting.senatemeeting",
                    ),
                ),
            ],
        ),
    ]
