# Generated by Django 4.2 on 2023-04-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annexure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("attachedPDF", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="SenateMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("officialID", models.IntegerField()),
                (
                    "announcement",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
                ("lastModified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SenatePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposal", models.CharField(blank=True, max_length=512, null=True)),
                ("resolution", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subPoints",
                        to="senateMeeting.senatepoint",
                    ),
                ),
            ],
        ),
    ]
