# Generated by Django 4.2 on 2023-04-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="senatepoint",
            old_name="approvalPending",
            new_name="approvalComplete",
        ),
    ]
