# Generated by Django 4.2 on 2023-04-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="senatemeeting", old_name="officialID", new_name="number",
        ),
    ]
