# Generated by Django 4.2 on 2023-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0002_rename_approvalpending_senatepoint_approvalcomplete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senatepoint",
            name="approvalComplete",
            field=models.BooleanField(default=False),
        ),
    ]
