# Generated by Django 4.2 on 2023-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0003_alter_annexure_senatemeeting_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="annexure", name="senateMeeting",),
        migrations.RemoveField(model_name="senatepoint", name="senateMeeting",),
    ]
