# Generated by Django 4.2 on 2023-04-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0002_handbooksection_name"),
        ("senateMeeting", "0003_alter_senatepoint_approvalcomplete"),
    ]

    operations = [
        migrations.AddField(
            model_name="senatepoint",
            name="handbookPointConfirmed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versionHistory",
                to="handbook.handbookpoint",
            ),
        ),
        migrations.AlterField(
            model_name="senatepoint",
            name="handbookPoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="handbook.handbookpoint",
            ),
        ),
    ]
