# Generated by Django 4.2 on 2023-04-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0004_senatepoint_handbookpointconfirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="senatemeeting",
            name="agendaFinalised",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="senatemeeting",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="senatemeeting",
            name="resolutionFinalised",
            field=models.BooleanField(default=False),
        ),
    ]
