# Generated by Django 4.2 on 2023-04-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0004_remove_annexure_senatemeeting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annexure",
            name="senateMeeting",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachedAnnexures",
                to="senateMeeting.senatemeeting",
            ),
        ),
        migrations.AddField(
            model_name="senatepoint",
            name="senateMeeting",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="senatePoints",
                to="senateMeeting.senatemeeting",
            ),
        ),
    ]
