# Generated by Django 4.2 on 2023-04-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0005_senatemeeting_agendafinalised_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annexure",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="annexure", name="number", field=models.IntegerField(),
        ),
    ]
