# Generated by Django 4.2 on 2023-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0006_annexure_id_alter_annexure_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="senatepoint",
            name="name",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="senatepoint",
            name="proposal",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="senatepoint",
            name="resolution",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
