# Generated by Django 4.2 on 2023-04-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0006_alter_annexure_senatemeeting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annexure",
            name="attachedPDF",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
