# Generated by Django 4.2 on 2023-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0007_alter_annexure_attachedpdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annexure",
            name="attachedPDF",
            field=models.FileField(default=None, null=True, upload_to="annexures/"),
        ),
    ]
