# Generated by Django 4.2 on 2023-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senateMeeting", "0007_senatepoint_name_alter_senatepoint_proposal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senatepoint",
            name="approved",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Approved"),
                    (1, "Not Approved"),
                    (2, "Rectified"),
                    (3, "Noted"),
                ],
                null=True,
            ),
        ),
    ]
