# Generated by Django 4.2 on 2023-04-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HandbookSection",
            fields=[
                ("number", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="HandbookPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("text", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "handbookSection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handbookPoints",
                        to="handbook.handbooksection",
                    ),
                ),
            ],
        ),
    ]
