# Generated by Django 4.2 on 2023-04-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="handbooksection",
            name="name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
