# Generated by Django 4.2 on 2023-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handbook", "0002_handbooksection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handbookpoint",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
