# Generated by Django 4.2 on 2023-04-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "position",
                    models.PositiveSmallIntegerField(choices=[(0, "Default")]),
                ),
                ("isStudent", models.BooleanField(default=False)),
            ],
        ),
    ]
