# Generated by Django 4.2 on 2023-04-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("senateMeeting", "0008_alter_annexure_attachedpdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Common To All"),
                            (1, "Computer Science"),
                            (2, "Electrical"),
                            (3, "Civil"),
                            (4, "Chemical"),
                        ]
                    ),
                ),
                ("batch", models.IntegerField()),
                (
                    "program",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "B. Tech"), (1, "M. Tech."), (2, "M. Design")]
                    ),
                ),
                (
                    "senateMeeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="introducedCurriculums",
                        to="senateMeeting.senatemeeting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "I"),
                            (1, "II"),
                            (2, "III"),
                            (3, "IV"),
                            (4, "V"),
                            (5, "VI"),
                            (6, "VII"),
                            (7, "VIII"),
                        ]
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="curriculum.curriculum",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("name", models.CharField(max_length=50)),
                ("credits", models.IntegerField()),
                ("nature", models.PositiveSmallIntegerField(choices=[])),
                ("type", models.PositiveSmallIntegerField(choices=[])),
                ("contents", models.CharField(max_length=512)),
                ("references", models.CharField(max_length=512)),
                ("objectives", models.CharField(max_length=512)),
                ("justification", models.CharField(max_length=512)),
                (
                    "preRequisites",
                    models.ManyToManyField(
                        related_name="preRequisiteOf", to="curriculum.course"
                    ),
                ),
            ],
        ),
    ]
