# Generated by Django 4.2 on 2023-04-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("senateMeeting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "B. Tech"), (1, "M. Tech."), (2, "M. Design")]
                    ),
                ),
                ("batch", models.IntegerField()),
                (
                    "branch",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Common To All"),
                            (1, "Computer Science"),
                            (2, "Electrical"),
                            (3, "Civil"),
                            (4, "Chemical"),
                        ]
                    ),
                ),
                (
                    "senateMeeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="introducedCurriculums",
                        to="senateMeeting.senatemeeting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "FIRST"),
                            (1, "SECOND"),
                            (2, "THIRD"),
                            (3, "FOURTH"),
                            (4, "FIFTH"),
                            (5, "SIXTH"),
                            (6, "SEVENTH"),
                            (7, "EIGHTH"),
                        ]
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="curriculum.curriculum",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("name", models.CharField(max_length=50)),
                ("credits", models.IntegerField()),
                ("nature", models.PositiveSmallIntegerField(choices=[(0, "Default")])),
                ("type", models.PositiveSmallIntegerField(choices=[(0, "Default")])),
                ("contents", models.CharField(blank=True, max_length=512, null=True)),
                ("references", models.CharField(blank=True, max_length=512, null=True)),
                ("objectives", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "justification",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "preRequisites",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="preRequisiteOf",
                        to="curriculum.course",
                    ),
                ),
                (
                    "semester",
                    models.ManyToManyField(
                        related_name="courses", to="curriculum.curriculum"
                    ),
                ),
            ],
        ),
    ]
