# Generated by Django 4.2 on 2023-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="contents",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="justification",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="nature",
            field=models.PositiveSmallIntegerField(choices=[(0, "Default")]),
        ),
        migrations.AlterField(
            model_name="course",
            name="objectives",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="preRequisites",
            field=models.ManyToManyField(
                null=True, related_name="preRequisiteOf", to="curriculum.course"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="references",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[(0, "Default")]),
        ),
        migrations.AlterField(
            model_name="semester",
            name="number",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "FIRST"),
                    (1, "SECOND"),
                    (2, "THIRD"),
                    (3, "FOURTH"),
                    (4, "FIFTH"),
                    (5, "SIXTH"),
                    (6, "SEVENTH"),
                    (7, "EIGHTH"),
                ]
            ),
        ),
    ]
