# Generated by Django 4.2 on 2023-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.ManyToManyField(
                related_name="courses", to="curriculum.semester"
            ),
        ),
    ]
