# Generated by Django 4.2 on 2023-04-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "curriculum",
            "0002_alter_course_contents_alter_course_justification_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preRequisites",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="preRequisiteOf",
                to="curriculum.course",
            ),
        ),
    ]
