# Generated by Django 4.2 on 2023-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_alter_course_prerequisites"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ManyToManyField(
                related_name="courses", to="curriculum.curriculum"
            ),
        ),
    ]
